language: python
python:
- '2.7'
- '3.6'
- 3.7-dev
- nightly
- pypy
- pypy3.5
os:
- linux
dist: trusty
sudo: required
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
    python: 3.6-dev
  - os: osx
    osx_image: xcode8.3
    python: 3.7-dev
  - os: osx
    osx_image: xcode8.3
    python: nightly
  allow_failures:
  - python: nightly
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash test/open_vcan.sh ; fi
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then travis_retry pip install -r doc/doc-requirements.txt;
  fi
- travis_retry pip install .[test]
script:
- pytest
- codecov
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then python -m sphinx -an doc build;
  fi

